spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/survey?createDatabaseIfNotExist=true
    username: root
    password: guidona
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

  liquibase:
    enabled: false
    change-log: classpath:config/liquibase/master.xml

file-export:
  enabled: false

#server:
#  ssl:
#    key-store-type: JKS
#    key-store: classpath:keystore/survey-app.jks
#    key-store-password: survey
#    key-alias: survey-app
#    enabled: true